version: '3.8'

services:
    backend:
        container_name: tp1-backend-srv
        build: ../backend-api/simple-api-student-main
        networks:
         - tp1-net
        depends_on:
         - database

    database:
        container_name: tp1-backend-db
        build: ../database
        networks:
         - tp1-net
        volumes:
         - tp1-data:/var/lib/postgresql/data

    httpd:
        container_name: tp1-http-index
        build: ../http-server
        ports:
         - 80:80
        networks:
         - tp1-net
        depends_on:
         - backend

networks:
  tp1-net:
volumes:
  tp1-data: